'use client';

import { useState } from 'react';
import { Header } from '@/components/layout/Header';
import { ProgressIndicator } from '@/components/layout/ProgressIndicator';
import { ProjectForm, ProjectData } from '@/components/forms/ProjectForm';
import { BlueprintUpload } from '@/components/forms/BlueprintUpload';
import { Alert } from '@/components/ui';

type Step = 'project' | 'input' | 'results';

const steps = [
  { id: 'project', name: 'Project', status: 'current' as const },
  { id: 'input', name: 'Blueprint', status: 'upcoming' as const },
  { id: 'results', name: 'Results', status: 'upcoming' as const },
];

export default function TestFlow() {
  const [currentStep, setCurrentStep] = useState<Step>('project');
  const [projectData, setProjectData] = useState<ProjectData | null>(null);
  const [error, setError] = useState<string>('');
  const [loading, setLoading] = useState(false);

  const updateSteps = (currentStepId: Step) => {
    return steps.map(step => {
      if (step.id === currentStepId) return { ...step, status: 'current' as const };
      if (steps.findIndex(s => s.id === currentStepId) > steps.findIndex(s => s.id === step.id)) {
        return { ...step, status: 'complete' as const };
      }
      return { ...step, status: 'upcoming' as const };
    });
  };

  const handleProjectSubmit = async (data: ProjectData) => {
    setLoading(true);
    setError('');
    
    try {
      // Add unique ID and timestamps
      const completeProjectData: ProjectData = {
        ...data,
        // These would normally be generated by backend
      };
      
      setProjectData(completeProjectData);
      
      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 500));
      
      if (data.inputMethod === 'blueprint') {
        setCurrentStep('input');
      } else {
        // Would go to manual entry forms
        alert('Manual entry forms coming next!');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  const handleUploadComplete = (jobId: string, fileNames: string[]) => {
    console.log('Upload complete:', jobId, fileNames);
    setCurrentStep('results');
    // Would normally navigate to results page
    alert(`Blueprint processed! Job ID: ${jobId}`);
  };

  const handleUploadError = (errorMessage: string) => {
    setError(errorMessage);
  };

  const handleBack = () => {
    setError('');
    if (currentStep === 'input') {
      setCurrentStep('project');
    }
  };

  const handleSwitchToManual = () => {
    if (projectData) {
      const updatedData = { ...projectData, inputMethod: 'manual' as const };
      setProjectData(updatedData);
      alert('Manual entry forms would go here!');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Header subtitle="Blueprint-First User Flow Test" />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <ProgressIndicator steps={updateSteps(currentStep)} />
        </div>
        
        {error && (
          <div className="mb-6">
            <Alert variant="error" title="Error">
              {error}
            </Alert>
          </div>
        )}
        
        {currentStep === 'project' && (
          <ProjectForm
            initialData={projectData || undefined}
            onSubmit={handleProjectSubmit}
            loading={loading}
          />
        )}
        
        {currentStep === 'input' && projectData && (
          <BlueprintUpload
            projectData={projectData}
            onUploadComplete={handleUploadComplete}
            onError={handleUploadError}
            onBack={handleBack}
            onSwitchToManual={handleSwitchToManual}
          />
        )}
        
        {currentStep === 'results' && (
          <div className="text-center">
            <h2 className="text-2xl font-bold mb-4">Results would go here!</h2>
            <p className="text-gray-600">This is where we'd show the HVAC calculations and recommendations.</p>
          </div>
        )}
      </div>
    </div>
  );
}