services:
  - type: web
    name: autohvac-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://autohvac-backend.onrender.com

  - type: web
    name: autohvac-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng libpoppler-utils poppler-utils libgl1-mesa-glx libglib2.0-0 libmupdf-dev mupdf-tools fonts-liberation fonts-dejavu-core file psmisc
      cd backend && pip install --only-binary=:all: -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    # IMPORTANT: You must manually attach the shared-storage disk to this service
    # in the Render dashboard with mount path: /var/data
    # This is required because Render doesn't support the disks: field for web services
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: autohvac-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: autohvac-postgres
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "2"
      # MUST match the mount path exactly - Render mounts at /var/data
      - key: RENDER_DISK_PATH
        value: /var/data
      # Optional: grace period for file cleanup (days)
      - key: FILE_CLEANUP_GRACE_DAYS
        value: "7"

  - type: worker
    name: autohvac-worker
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng libpoppler-utils poppler-utils libgl1-mesa-glx libglib2.0-0 libmupdf-dev mupdf-tools fonts-liberation fonts-dejavu-core file psmisc
      cd backend && pip install --only-binary=:all: -r requirements.txt
    # Import both task modules
    startCommand: cd backend && celery -A tasks worker --loglevel=info --concurrency=2 --max-tasks-per-child=50 --max-memory-per-child=512000 --time-limit=1800 --soft-time-limit=1740 --without-gossip --without-mingle --without-heartbeat
    # IMPORTANT: You must manually attach the shared-storage disk to this worker
    # in the Render dashboard with mount path: /var/data
    # This is required because Render doesn't support the disks: field in YAML
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: autohvac-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: autohvac-postgres
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: C_FORCE_ROOT
        value: "true"
      # MUST be the same as backend to access the same files
      - key: RENDER_DISK_PATH
        value: /var/data
      # Optional: grace period for file cleanup (days)
      - key: FILE_CLEANUP_GRACE_DAYS
        value: "7"
    autoDeploy: false

  - type: redis
    name: autohvac-redis
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
    plan: starter

databases:
  - name: autohvac-postgres
    databaseName: autohvac
    user: autohvac
    plan: starter