"""Add Manual J assumptions to projects table

Revision ID: 769d7e700a57
Revises: d660aa73c6e5
Create Date: 2025-07-27 20:17:16.045761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '769d7e700a57'
down_revision: Union[str, None] = 'd660aa73c6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('duct_config', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projects', sa.Column('heating_fuel', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projects', sa.Column('assumptions_collected', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'assumptions_collected')
    op.drop_column('projects', 'heating_fuel')
    op.drop_column('projects', 'duct_config')
    # ### end Alembic commands ###
