"""Add parsed_schema_json field and fix Postgres compatibility

Revision ID: cf60711350c0
Revises: d988b352b564
Create Date: 2025-07-27 20:27:49.264438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf60711350c0'
down_revision: Union[str, None] = 'd988b352b564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('parsed_schema_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'parsed_schema_json')
    # ### end Alembic commands ###
